# Generated by Django 3.2.18 on 2023-04-27 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
import leave.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('days', models.IntegerField(verbose_name='Jours')),
            ],
            options={
                'verbose_name': 'Type de congé',
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Mise à jour le')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('start_period', models.DateField(help_text='YYYY-MM-DD', verbose_name='Période de départ')),
                ('end_period', models.DateField(help_text='YYYY-MM-DD', verbose_name='Période de fin')),
                ('reason', models.TextField(default='-', verbose_name='Raison')),
                ('observation', models.TextField(default='-', verbose_name='Observation')),
                ('document', models.FileField(blank=True, default=None, null=True, upload_to=leave.models.upload_directory_file, verbose_name='Document')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
                ('type_of', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave.typeofleave', verbose_name='Type de congé')),
            ],
            options={
                'verbose_name': 'Congé',
            },
        ),
    ]
