# Generated by Django 3.2.18 on 2023-04-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_approval_approver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='model',
            field=models.CharField(choices=[('exit.exit', 'Approbation sur la sortie'), ('leave.leave', 'Approbation sur le congé'), ('logistic.requisition', 'Approbation sur requisition'), ('social.fundrequest', 'Approbation sur demande de fonds')], max_length=30, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='approver',
            name='model',
            field=models.CharField(choices=[('exit.exit', 'Approbation sur la sortie'), ('leave.leave', 'Approbation sur le congé'), ('logistic.requisition', 'Approbation sur requisition'), ('social.fundrequest', 'Approbation sur demande de fonds')], max_length=30, verbose_name='Model'),
        ),
    ]
