# Generated by Django 3.2.18 on 2023-04-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20230430_1752'),
        ('core', '0003_auto_20230428_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='branches',
            field=models.ManyToManyField(blank=True, to='employee.Branch', verbose_name='Branche'),
        ),
        migrations.AlterUniqueTogether(
            name='approver',
            unique_together={('model', 'employee')},
        ),
    ]
