# Generated by Django 3.2.18 on 2023-04-27 10:04

from django.db import migrations, models
import django.db.models.deletion
import employee.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
            ],
            options={
                'verbose_name': 'Agreement',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
            ],
            options={
                'verbose_name': 'Site',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
            ],
            options={
                'verbose_name': 'Direction',
            },
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('working_days', models.IntegerField(default=0, verbose_name='Jours de travail')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
            ],
            options={
                'verbose_name': 'Fonction',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
            ],
            options={
                'verbose_name': 'Grade',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
            ],
            options={
                'verbose_name': 'Mode de paiement',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
            ],
            options={
                'verbose_name': 'Service',
            },
        ),
        migrations.CreateModel(
            name='SubDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
            ],
            options={
                'verbose_name': 'Sous-Direction',
            },
        ),
        migrations.CreateModel(
            name='Syndicat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
            ],
            options={
                'verbose_name': 'Syndicat',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(blank=True, default=None, null=True, upload_to=employee.models.upload_directory_file)),
                ('matricule', models.CharField(default=None, max_length=100, null=True, unique=True, verbose_name='Matricule')),
                ('agreement', models.CharField(choices=[(None, '-')], default=None, max_length=10, null=True, verbose_name='Type de contrat')),
                ('first_name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Prenom')),
                ('middle_name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Deuxième prénom')),
                ('last_name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Nom')),
                ('n_cnss', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='N. CNSS')),
                ('n_inpp', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='N. INPP')),
                ('n_onem', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='N. ONEM')),
                ('gender', models.CharField(choices=[('Male', 'Homme'), ('Female', 'Femme')], default='Male', max_length=10, null=True, verbose_name='Genre')),
                ('marital_status', models.CharField(choices=[('Maried', 'Marie'), ('Single', 'Celibataire'), ('Widower', 'Veuf(ve)')], default='Celibataire', max_length=12, verbose_name='Etat civil')),
                ('dob', models.DateField(blank=True, default=None, help_text='YYYY-MM-DD', null=True, verbose_name='Date de naissance')),
                ('doj', models.DateField(blank=True, default=None, help_text='YYYY-MM-DD', null=True, verbose_name="Date d'entrée en fonction")),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, null=True, region=None, verbose_name='Numéro de mobile')),
                ('address', models.TextField(blank=True, default=None, null=True, verbose_name='Adresse permanente')),
                ('emergency_information', models.TextField(default=None, null=True, verbose_name="Information de contact d'urgence")),
                ('syndicate', models.CharField(blank=True, choices=[(None, '-')], default=None, max_length=10, null=True, verbose_name='Syndicat')),
                ('branch', models.CharField(choices=[(None, '-')], max_length=10, verbose_name='Branch')),
                ('payment_method', models.CharField(choices=[(None, '-')], max_length=10, verbose_name='Mode de paiement')),
                ('payer_name', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Nom de la banque/Agent payeur')),
                ('pay_account', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Numero de compte')),
                ('comment', models.TextField(blank=True, default=None, null=True, verbose_name='Commentaire')),
                ('status', models.CharField(choices=[('Actif', 'Actif'), ('Indisponibilite', 'Indisponibilite'), ('Licenciement', 'Licenciement'), ('Inactif', 'Inactif')], default='Actif', max_length=20, verbose_name='Status')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Mise à jour le')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('direction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.direction', verbose_name='Direction')),
                ('function', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.function', verbose_name='Fonction')),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.grade', verbose_name='Grade')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.service', verbose_name='Service')),
                ('subDirection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.subdirection', verbose_name='Sous-Direction/Technostructure')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('doc', models.FileField(upload_to=employee.models.upload_directory_file, verbose_name='Document')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Mise à jour le')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Document',
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('dob', models.DateField(help_text='YYYY-MM-DD', verbose_name='Date de naissance')),
                ('birth_certificate', models.FileField(upload_to=employee.models.upload_directory_file, verbose_name='Attestation de naissance')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Mise à jour le')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Enfant',
            },
        ),
    ]
