# Generated by Django 3.2.18 on 2023-04-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='spouse',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Nom du cojoint'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='agreement',
            field=models.CharField(choices=[(None, '-'), ('CDI', 'CDI'), ('CDD', 'CDD')], default=None, max_length=10, null=True, verbose_name='Type de contrat'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='branch',
            field=models.CharField(choices=[(None, '-'), ('Kinshasa', 'Kinshasa'), ('Lubumbashi', 'Lubumbashi')], max_length=10, verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='payment_method',
            field=models.CharField(choices=[(None, '-'), ('Banque', 'Banque'), ('Caisse', 'Caisse')], max_length=10, verbose_name='Mode de paiement'),
        ),
    ]
