# Generated by Django 3.2.18 on 2023-04-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20230428_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='spouse',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Nom du cojoint(e)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('actif', 'Actif'), ('indisponibilite', 'Indisponibilite'), ('licenciement', 'Licenciement'), ('inactif', 'Inactif')], default='actif', max_length=20, verbose_name='Status'),
        ),
    ]
