# Generated by Django 3.2.18 on 2023-05-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20230502_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Post nom'),
        ),
    ]
