# Generated by Django 3.2.18 on 2023-05-08 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employee_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='subDirection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.subdirection', verbose_name='Sous-Direction/Technostructure'),
        ),
    ]
