# Generated by Django 3.2.18 on 2023-05-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20230508_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='agreement',
            field=models.CharField(choices=[(None, '-')], default=None, max_length=10, null=True, verbose_name='Type de contrat'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='branch',
            field=models.CharField(choices=[(None, '-')], max_length=10, verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='payment_method',
            field=models.CharField(choices=[(None, '-')], max_length=10, verbose_name='Mode de paiement'),
        ),
    ]
