# Generated by Django 3.2.18 on 2023-04-27 12:19

from django.db import migrations, models
import social.models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundrequest',
            name='doc',
            field=models.FileField(blank=True, default=None, null=True, upload_to=social.models.upload_directory_file, verbose_name='Document'),
        ),
    ]
