# Generated by Django 3.2.18 on 2023-04-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_fundrequest_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=5, verbose_name='Montant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundrequest',
            name='currency',
            field=models.CharField(choices=[('CDF', 'CDF'), ('USD', 'USD')], default='CDF', max_length=25, verbose_name='Devise'),
        ),
    ]
