# Generated by Django 3.2.18 on 2023-04-30 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20230427_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundrequest',
            options={'verbose_name': 'Demande de fond'},
        ),
    ]
